import datetime
z=datetime.datetime(2000,10,13)
print(z.strftime("%a"))
print(z.strftime("%A"))
print(z.strftime("%w"))
print(z.strftime("%d"))
print(z.strftime("%b"))
print(z.strftime("%B"))
print(z.strftime("%Y"))
print(z.strftime("%y"))
print(z.strftime("%I"))
print(z.strftime("%H"))
print(z.strftime("%p"))
print(z.strftime("%C"))